appName: vita
namespace: vita

image:
  repository: docker.yesidlopez.de/vita
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: LoadBalancer
  port: 80

readinessProbe:
  httpGet:
    path: /health
    port: http
