apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        name: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "vita/websocket_server/server.py"]
          env:
            - name: WEBSOCKET_HOST
              value: "{{ .Values.websocket.host }}"
            - name: WEBSOCKET_PORT
              value: "{{ .Values.websocket.port }}"
          # - name: OPENAI_API_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: openai
          #       key: key
          ports:
            - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
        - name: my-registry-secret
