
input:
  label: glucose
  kafka:
    addresses: [ "${KAFKA_BROKER}" ]
    topics: [ glucose-window ]
    consumer_group: "glucose-consumer"
    tls:
      enabled: true
    sasl:
      mechanism: "${KAFKA_SASL_MECHANISM}"
      user: "${KAFKA_USERNAME}"
      password: "${KAFKA_PASSWORD}"

pipeline:
  processors:
  - mapping: |
      root = if this.glucose.mean > 70 && this.glucose.mean <= 180 { deleted() }
  - branch: 
      processors:
        - openai_chat_completion:
            server_address: http://192.168.2.224:8000/v3
            api_key: "any" # No default (required)
            model: meta-llama/Meta-Llama-3-8B-Instruct
            prompt: |
              Consider the glucose level ${!this.glucose.mean}
              
              Give me specific advice on how to improve the glucose level in less than 2 short sentences.
      result_map: |
        root.advice = content().string()
  - mapping: |
      root.risk = if this.glucose.mean > 150 {
        "hyperglycemia"
      } else if this.glucose.mean < 70 {
        "hypoglycemia"
      }
      root.bg = this.glucose.mean
      root.ts = this.time
      root.advice = this.advice
output:
  label: risks
  kafka:
    addresses: [ "${KAFKA_BROKER}" ]
    tls:
      enabled: true
    sasl:
      mechanism: "${KAFKA_SASL_MECHANISM}"
      user: "${KAFKA_USERNAME}"
      password: "${KAFKA_PASSWORD}"
    topic: risk
