from dotenv import load_dotenv
from os import getenv

load_dotenv()

KAFKA_TOPIC = getenv("KAFKA_TOPIC")
KAFKA_BROKER = getenv("KAFKA_BROKER")
KAFKA_USERNAME = getenv("KAFKA_USERNAME")
KAFKA_PASSWORD = getenv("KAFKA_PASSWORD")
KAFKA_SECURITY_PROTOCOL = getenv("KAFKA_SECURITY_PROTOCOL")
KAFKA_SASL_MECHANISM = getenv("KAFKA_SASL_MECHANISM")

WEBSOCKET_HOST = getenv("WEBSOCKET_HOST")
WEBSOCKET_PORT = getenv("WEBSOCKET_PORT")
WEBSOCKET_URI = f"ws://{WEBSOCKET_HOST}:{WEBSOCKET_PORT}"
